### ISSUE TITLE
Sanity check items

### ISSUE THREAD

**Issue by stuaxo** [stuaxo/cairo-list#10]
Noticed a link to my fork of cairocks - will give everything a quick check.

**Comment by rjopek** [comment]
You need to remove the fork to avoid the double name cairo-list

**Comment by stuaxo** [comment]
Yep, I did this - just leaving myself a task todo :)

**Comment by rjopek** [comment]
Resent.

**Comment by stuaxo** [comment]
Thanks, got it - a lot of my dev mails don't go to my ordinary mail, so it doesn't get overwhelmed.

**Comment by stuaxo** [comment]
- [x] Fix Cairou Link
- [x] Remove "Cairo" smart contract thingy
