### ISSUE TITLE
Cairo-list

### ISSUE THREAD

**Issue by rjopek** [stuaxo/cairo-list#9]
Hi Stuart,

If you are interested I can transfer this repository to you @stuaxo.
These repositories have been adopted by others:

[harbour-list](https://github.com/Petewg/harbour-list)
[jekyll-list](https://github.com/elotroalex/jekyll-list)

--Rafał

**Comment by stuaxo** [comment]
I'd be happy to; I think it makes sense to move it to it's own organisation (in future maybe we can get it under freedesktop - but for now, building a useful resource makes sense).

While I don't have much free time; I do spend some of it keeping up with linux graphics + cairo.

**Comment by rjopek** [comment]
1. Okay, remove your fork and let me know (because the names are double)
2. then, i do a repository transfer.

**Comment by stuaxo** [comment]
Removed; I created a new org for it to live under 
https://github.com/orgs/cairographics-list/

**Comment by rjopek** [comment]
In my opinion, the name without the suffix is better:
`cairographics`

**Comment by rjopek** [comment]
all Cairo-related projects can be placed there

**Comment by rjopek** [comment]
The name is free

https://github.com/cairographics

**Comment by stuaxo** [comment]
It might make sense for this to live under the cairo org at freedesktop -
https://gitlab.freedesktop.org/cairo/

I know it's hard to get feedback on the cairo mailinglist; I think I'd like to ask the devs again, before that -

I want to see if I can add some automation, for things like checking links, and linting, this should make it harder for me to accidentally break the list.

**Comment by rjopek** [comment]
This is the best idea.

**Comment by rjopek** [comment]
Or right here -

https://github.com/freedesktop

**Comment by stuaxo** [comment]
I might be wrong at this point, but I thought all those repos were mirrors of the ones on gitlab ?

Still; there definitely are some projects here - libepoxy and the ones under pygobject spring to mind.

**Comment by rjopek** [comment]
Well, then I don't know what to say.

**Comment by stuaxo** [comment]
It might not be out of the question to live there - I don't expect this to be the final spot; this is definitely a question to come back to.

First thing to do is get the automation sorted + hopefully it will be bits the other lists you started can apply.

I'll probably reach out to the devs on the list, this'll raise a little awareness + they may have ideas on the question of where this goes too.
